== The story behind this solution pattern

Kubernetes is an open-source container orchestration engine for automating deployment, scaling and management of containerized applications. It is being used heavily for production grade applications. Kubernetes clusters are being created and used in public and private clouds. Managing 100s of clusters across multi-cloud and running 1000s of applications on those clusters is cumbersome. Using GitOps(ArgoCD) and RedHat ACM, we can manage multiple kubernetes clusters as well as deployments of applications on those clusters. Majority of the applications need persistent storage. RedHat provides ODF as software defined storage solution which can be deployed across multiple clusters through GitOps.

== The Solution

This solution pattern uses GitOps(ArgoCD) to manage Openshift Clusters and applications. ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes. ArgoCD follows the GitOps pattern of using Git repos as source of truth for defining the desired application state. Kubernetes manifests can be specified in several ways: kustomize or helm charts or jsonnet or yaml files. ArgoCD automates the deployment of the desired application states in the specified target environments. Application deployments can track updates to branches, tags or pinned to a specific version of manifests at a Git commit. In addition to this, multiple openshift clusters, running in hybrid cloud can be managed using RedHat ACM. RedHat ODF is also deployed and configured through ArgoCD in multiple clusters as per the requirement.
    