= Solution Pattern: Name Template
:sectnums:
:sectlinks:
:doctype: book

= See the Solution in Action

== Demonstration

Demo is split into two parts:

* Bootstrapping ODF Multicloud GitOps Part 1 : This video demonstrates Hub Cluster setup, ArgoCD deployment and import of the existing openshift clusters. Once clusters are imported, these managed clusters will be managed by RedHat ACM.

* Bootstrapping ODF Mutlicloud GitOps Part 2 - AWS, GCP and Azure : This video demonstrates ODF installation on Hub as well as Managed clusters and RedHat Quay installation on the Hub Cluster.

[#demo-video]
=== Watch a demonstration

Bootstrapping ODF Multicloud GitOps Part 1

video::vLgpsfsA-9k[youtube, width=800, height=480]

Bootstrapping ODF Mutlicloud GitOps Part 2 - AWS, GCP and Azure

video::Tl0-3Xqgu84[youtube, width=800, height=480]


== Run the demonstration

=== Before getting started
To run this demo, you will need xpto. Adding to that, make sure to have:

* ABC
* XYZ
* XPTO

=== Installing the demo
Installation guide and basic test of the demo installation if needed

=== Walkthrough guide
How to run through the demo
