= Solution Pattern: Name Template
:sectnums:
:sectlinks:
:doctype: book
:page-toclevels: 3

= See the Solution in Action

== Demonstration

Demo is split into two parts:

* Bootstrapping ODF Multicloud GitOps Part 1 : This video demonstrates Hub Cluster setup, ArgoCD deployment and import of the existing openshift clusters. Once clusters are imported, these managed clusters will be managed by RedHat ACM.

* Bootstrapping ODF Mutlicloud GitOps Part 2 - AWS, GCP and Azure : This video demonstrates ODF installation on Hub as well as Managed clusters and RedHat Quay installation on the Hub Cluster.

[#demo-video]
=== Watch a demonstration

Bootstrapping ODF Multicloud GitOps Part 1

video::vLgpsfsA-9k[youtube, width=800, height=480]

Bootstrapping ODF Mutlicloud GitOps Part 2 - AWS, GCP and Azure

video::Tl0-3Xqgu84[youtube, width=800, height=480]


== Run the demonstration

=== Before getting started
To run this demo, we will need the following:

* An Openshift cluster to be used as Hub Cluster(We are using Openshift Cluster deployed on AWS). 
* A second OpenShift cluster to be imported and managed by Hub Cluster(Cluster can be in GCP or Azure).
* Helm

=== Installing the demo
We will need the following tools to deploy the demo:

* make
* sh
* oc 
* git
* ansible 
* kubernetes.core collection for ansible

To check if you have the cli tools, you can open your terminal and use following commands:

[.console-input]
[source,shell script]
```
oc version
make --version
git version
ansible --version 
ansible-galaxy --version 
ansible-galaxy collection list #the list should include kubernetes.core
```

If you can't see `kubernetes.core` collection listed, you can install it with `ansible-galaxy`:

[.console-input]
[source,shell script]
```
$ ansible-galaxy collection install kubernetes.core
```

=== Walkthrough guide

How to run through the demo
